conflict seeker - nearing the end

diff --git a/.github/workflows/conflict_seeker.yaml b/.github/workflows/conflict_seeker.yaml
--- a/.github/workflows/conflict_seeker.yaml
+++ b/.github/workflows/conflict_seeker.yaml
@@ -29,17 +29,19 @@ jobs:
           # Clear open_prs
           echo "" > open_prs.txt
           
-          # Get open PRs' HEADs
+          # Get open PRs' numbers
           if open_ids=`curl -L \
             -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer ${{ env.TOKEN }}" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
             https://api.github.com/repos/${{ env.OWNER }}/${{ env.REPO }}/pulls \
             | jq -r .[].number`; then
-            echo "$open_ids"
+            echo "Scraped the following numbers: $open_ids"
             
           fi
           
+          # Iterate through the numbers, scrape additional information,
+          # construct a JSON object and save it in an env file
           while IFS= read -r line; do
             
             if [ -z "$line" ]; then
@@ -54,17 +56,8 @@ jobs:
               -H "X-GitHub-Api-Version: 2022-11-28" \
               https://api.github.com/repos/${{ env.OWNER }}/${{ env.REPO }}/pulls/${line}\
               | jq -r .head.sha`; then
-              echo `curl -L \
-              -H "Accept: application/vnd.github+json" \
-              -H "Authorization: Bearer ${{ env.TOKEN }}" \
-              -H "X-GitHub-Api-Version: 2022-11-28" \
-              https://api.github.com/repos/${{ env.OWNER }}/${{ env.REPO }}/pulls/${line}`
+              
             fi
-              echo `curl -L \
-              -H "Accept: application/vnd.github+json" \
-              -H "Authorization: Bearer ${{ env.TOKEN }}" \
-              -H "X-GitHub-Api-Version: 2022-11-28" \
-              https://api.github.com/repos/${{ env.OWNER }}/${{ env.REPO }}/pulls/${line}`
             
             if open_branch_name=`curl -L \
               -H "Accept: application/vnd.github+json" \
@@ -84,11 +77,15 @@ jobs:
               echo "$open_url"
             fi
             
+            # If information was scraped successfully, construct a JSON object,
+            # and save it in an env file.
             if [[ "$open_url" && "$open_branch_name" && "$open_head" ]]; then
               data_json="{\"name\": \"$open_branch_name\", \"head\": \"$open_head\", \"url\": \"$open_url\"}"
               echo "$data_json" >> open_prs.txt
               printf "SAVED "
               printf "$data_json"
+            else
+              echo "Couldn't scrape information about pull request $line"
             fi
           done <<< "$open_ids"
 
@@ -96,7 +93,7 @@ jobs:
       - name: upload open PR commit HEADs
         uses: actions/upload-artifact@v4
         with:
-          name: open_prs
+          name: open_prs # Must match with download
           path: open_prs.txt
 
   # job #2 - Download the artifacts and use the data to compare changes between potentially divergent branches.
@@ -110,7 +107,7 @@ jobs:
       - name: Get Repository
         uses: actions/checkout@v4
         
-        # Sign in with username and email, rebase local branch and checkout to main,
+        # Sign in with username and email and rebase main onto the local branch,
         # Necessary to access the repository.
       - name: Pull Latest Changes
         shell: bash
@@ -128,8 +125,7 @@ jobs:
       - name: Retrieve Open PR's
         uses: actions/download-artifact@v4
         with:
-          # Must match
-          name: open_prs
+          name: open_prs # Must match with upload
         
         # Scrape repository secrets and setup environment variables.
       - shell: bash
@@ -154,10 +150,12 @@ jobs:
               if [ -z "$line" ]; then
                 continue
               else
-                branch_name=`git branch -r --contains "${line}"`
-                git rebase "$line"|| { \
+                name = `echo $line | jq.name`
+                head = `echo $line | jq.head`
+                url = `echo $line | jq.url`
+                git rebase "$head"|| { \
                 curl -H "Content-Type: application/json" -X POST -d \
-                '{"username": "Conflict Seeker", "content": "'"**[CONFLICTING VERSIONS FOUND]** \n\n**Rebase Order:** \n ${successful_rebases} \n **Conflict occurred** while rebasing ${line} (`echo ${branch_name}`)"'"}' \
+                '{"username": "Conflict Seeker", "content": "'"**[CONFLICTING VERSIONS FOUND]** \n\n**Rebase Order:** \n ${successful_rebases} \n **Conflict occurred** while rebasing ${head} (${name}), \n ${url} "'"}' \
                 "${WEBHOOK}"; 
                 exit 1;
                 }
